package x64

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!
// go build -o ./gen/gen ./gen/gen.go && ./gen/gen patterns > ./x86.generated.go

// Operand type/size patterns
//
// i : immediate
// o : instruction offset
//
// m : memory
// k : vsib addressing, 32 bit result, size determines xmm or ymm
// l : vsib addressing, 64 bit result, size determines xmm or ymm
//
// r : legacy reg
// f : fp reg
// x : mmx reg
// y : xmm/ymm reg
// s : segment reg
// c : control reg
// d : debug reg
// b : bound reg
//
// v : r and m
// u : x and m
// w : y and m
//
// A ... P: match rax - r15
// Q ... V: match es, cs, ss, ds, fs, gs
// W: matches CR8
// X: matches st0
//
// b, w, d, q, o, h match a byte, word, doubleword, quadword, octword and hexadecword
// p matches a PWORD (10 bytes)
// f matches an FWORD (6 bytes)
// 0 matches all possible sizes for this operand (w/d for i, w/d/q for r/v, o/h for y/w and everything for m)
// 1 matches a lack of size, only useful in combination with m
const (
	argp_ uint8 = iota
	argp_Aw
	argp_Uw
	argp_Vw
	argp_fp
	argp_ib
	argp_id
	argp_iw
	argp_m1
	argp_m0
	argp_mb
	argp_md
	argp_mo
	argp_mp
	argp_mq
	argp_mw
	argp_ob
	argp_od
	argp_r0
	argp_rb
	argp_rd
	argp_rq
	argp_rw
	argp_v0
	argp_vb
	argp_vd
	argp_A0i0
	argp_A0r0
	argp_AbCw
	argp_Abib
	argp_Abiq
	argp_AdBd
	argp_AdCw
	argp_Adib
	argp_Adiq
	argp_AqBd
	argp_Aqiq
	argp_AwCw
	argp_Awib
	argp_Awiq
	argp_CwAb
	argp_CwAd
	argp_CwAw
	argp_Wdrd
	argp_Wqrq
	argp_Xpfp
	argp_bobo
	argp_bom1
	argp_borq
	argp_cdrd
	argp_cqrq
	argp_ddrd
	argp_dqrq
	argp_fpXp
	argp_ibAb
	argp_ibAd
	argp_ibAw
	argp_iqAb
	argp_iqAd
	argp_iqAq
	argp_iqAw
	argp_iwib
	argp_m1bo
	argp_m1yo
	argp_m0i0
	argp_m0ib
	argp_m0r0
	argp_m0y0
	argp_mbib
	argp_mbrb
	argp_mdrd
	argp_mdyo
	argp_mhyh
	argp_moyo
	argp_mpsw
	argp_mqrq
	argp_mqxq
	argp_mqyo
	argp_mwsw
	argp_r0A0
	argp_r0i0
	argp_r0ib
	argp_r0m1
	argp_r0m0
	argp_r0md
	argp_r0mq
	argp_r0mw
	argp_r0r0
	argp_r0sw
	argp_r0v0
	argp_r0vb
	argp_r0vw
	argp_r0y0
	argp_r0yo
	argp_rbib
	argp_rbmb
	argp_rbrb
	argp_rbvb
	argp_rdWd
	argp_rdcd
	argp_rddd
	argp_rdid
	argp_rdmd
	argp_rdmq
	argp_rdvw
	argp_rdxq
	argp_rdyo
	argp_rqWq
	argp_rqcq
	argp_rqdq
	argp_rqiq
	argp_rqmd
	argp_rqmo
	argp_rqmq
	argp_rqvd
	argp_rqvq
	argp_rqyo
	argp_rwiw
	argp_rwmb
	argp_swmp
	argp_swmw
	argp_swrw
	argp_uqxq
	argp_v0Bb
	argp_v0i0
	argp_v0ib
	argp_v0r0
	argp_vbBb
	argp_vbib
	argp_vbrb
	argp_vdxq
	argp_vdyo
	argp_vqrq
	argp_vqxq
	argp_vqyo
	argp_whyh
	argp_woyo
	argp_xqib
	argp_xqmq
	argp_xquq
	argp_xqvd
	argp_xqvq
	argp_xqwo
	argp_xqxq
	argp_xqyo
	argp_y0m0
	argp_y0mb
	argp_y0md
	argp_y0mw
	argp_y0w0
	argp_y0wo
	argp_y0yo
	argp_yhmh
	argp_yhmo
	argp_yhmq
	argp_yhwh
	argp_yhyo
	argp_yoib
	argp_yom1
	argp_yom0
	argp_yomd
	argp_yomo
	argp_yomq
	argp_yomw
	argp_youq
	argp_yovd
	argp_yovq
	argp_yowo
	argp_yoxq
	argp_yoy0
	argp_yoyo
	argp_A0BdCd
	argp_AqBdCd
	argp_m0y0y0
	argp_mbyoib
	argp_mqyoib
	argp_mwyoib
	argp_r0r0v0
	argp_r0v0i0
	argp_r0v0ib
	argp_r0v0id
	argp_r0v0r0
	argp_rdxqib
	argp_rdyoib
	argp_rqyoib
	argp_v0r0Bb
	argp_v0r0ib
	argp_vdyoib
	argp_vqyoib
	argp_woy0ib
	argp_woyhib
	argp_xqm1ib
	argp_xqrdib
	argp_xquqib
	argp_xqvwib
	argp_y0k0y0
	argp_y0l0y0
	argp_y0loy0
	argp_y0w0ib
	argp_y0y0ib
	argp_y0y0m0
	argp_y0y0w0
	argp_y0y0wo
	argp_yhwhib
	argp_yhyhwh
	argp_yoibib
	argp_yok0yo
	argp_yom1ib
	argp_yomdib
	argp_yomqib
	argp_yomwib
	argp_yordib
	argp_yorwib
	argp_yovbib
	argp_yovdib
	argp_yovqib
	argp_yowoib
	argp_yowoyo
	argp_yoyoib
	argp_yoyomd
	argp_yoyomq
	argp_yoyov0
	argp_yoyowo
	argp_yoyoyo
	argp_y0y0w0ib
	argp_y0y0w0y0
	argp_y0y0y0w0
	argp_yhyhwhib
	argp_yhyhwoib
	argp_yoyoibib
	argp_yoyomdib
	argp_yoyomdyo
	argp_yoyomqib
	argp_yoyomqyo
	argp_yoyordib
	argp_yoyovbib
	argp_yoyovdib
	argp_yoyovqib
	argp_yoyovwib
	argp_yoyowoib
	argp_yoyowoyo
	argp_yoyoyoib
	argp_yoyoyomd
	argp_yoyoyomq
	argp_yoyoyowo
	argp_yoyoyoyo
)

var argpFormats = [...][8]byte{
	[8]byte{0, 0, 0, 0, 0, 0, 0, 0},
	[8]byte{'A', 'w', 0, 0, 0, 0, 0, 0},
	[8]byte{'U', 'w', 0, 0, 0, 0, 0, 0},
	[8]byte{'V', 'w', 0, 0, 0, 0, 0, 0},
	[8]byte{'f', 'p', 0, 0, 0, 0, 0, 0},
	[8]byte{'i', 'b', 0, 0, 0, 0, 0, 0},
	[8]byte{'i', 'd', 0, 0, 0, 0, 0, 0},
	[8]byte{'i', 'w', 0, 0, 0, 0, 0, 0},
	[8]byte{'m', '1', 0, 0, 0, 0, 0, 0},
	[8]byte{'m', '0', 0, 0, 0, 0, 0, 0},
	[8]byte{'m', 'b', 0, 0, 0, 0, 0, 0},
	[8]byte{'m', 'd', 0, 0, 0, 0, 0, 0},
	[8]byte{'m', 'o', 0, 0, 0, 0, 0, 0},
	[8]byte{'m', 'p', 0, 0, 0, 0, 0, 0},
	[8]byte{'m', 'q', 0, 0, 0, 0, 0, 0},
	[8]byte{'m', 'w', 0, 0, 0, 0, 0, 0},
	[8]byte{'o', 'b', 0, 0, 0, 0, 0, 0},
	[8]byte{'o', 'd', 0, 0, 0, 0, 0, 0},
	[8]byte{'r', '0', 0, 0, 0, 0, 0, 0},
	[8]byte{'r', 'b', 0, 0, 0, 0, 0, 0},
	[8]byte{'r', 'd', 0, 0, 0, 0, 0, 0},
	[8]byte{'r', 'q', 0, 0, 0, 0, 0, 0},
	[8]byte{'r', 'w', 0, 0, 0, 0, 0, 0},
	[8]byte{'v', '0', 0, 0, 0, 0, 0, 0},
	[8]byte{'v', 'b', 0, 0, 0, 0, 0, 0},
	[8]byte{'v', 'd', 0, 0, 0, 0, 0, 0},
	[8]byte{'A', '0', 'i', '0', 0, 0, 0, 0},
	[8]byte{'A', '0', 'r', '0', 0, 0, 0, 0},
	[8]byte{'A', 'b', 'C', 'w', 0, 0, 0, 0},
	[8]byte{'A', 'b', 'i', 'b', 0, 0, 0, 0},
	[8]byte{'A', 'b', 'i', 'q', 0, 0, 0, 0},
	[8]byte{'A', 'd', 'B', 'd', 0, 0, 0, 0},
	[8]byte{'A', 'd', 'C', 'w', 0, 0, 0, 0},
	[8]byte{'A', 'd', 'i', 'b', 0, 0, 0, 0},
	[8]byte{'A', 'd', 'i', 'q', 0, 0, 0, 0},
	[8]byte{'A', 'q', 'B', 'd', 0, 0, 0, 0},
	[8]byte{'A', 'q', 'i', 'q', 0, 0, 0, 0},
	[8]byte{'A', 'w', 'C', 'w', 0, 0, 0, 0},
	[8]byte{'A', 'w', 'i', 'b', 0, 0, 0, 0},
	[8]byte{'A', 'w', 'i', 'q', 0, 0, 0, 0},
	[8]byte{'C', 'w', 'A', 'b', 0, 0, 0, 0},
	[8]byte{'C', 'w', 'A', 'd', 0, 0, 0, 0},
	[8]byte{'C', 'w', 'A', 'w', 0, 0, 0, 0},
	[8]byte{'W', 'd', 'r', 'd', 0, 0, 0, 0},
	[8]byte{'W', 'q', 'r', 'q', 0, 0, 0, 0},
	[8]byte{'X', 'p', 'f', 'p', 0, 0, 0, 0},
	[8]byte{'b', 'o', 'b', 'o', 0, 0, 0, 0},
	[8]byte{'b', 'o', 'm', '1', 0, 0, 0, 0},
	[8]byte{'b', 'o', 'r', 'q', 0, 0, 0, 0},
	[8]byte{'c', 'd', 'r', 'd', 0, 0, 0, 0},
	[8]byte{'c', 'q', 'r', 'q', 0, 0, 0, 0},
	[8]byte{'d', 'd', 'r', 'd', 0, 0, 0, 0},
	[8]byte{'d', 'q', 'r', 'q', 0, 0, 0, 0},
	[8]byte{'f', 'p', 'X', 'p', 0, 0, 0, 0},
	[8]byte{'i', 'b', 'A', 'b', 0, 0, 0, 0},
	[8]byte{'i', 'b', 'A', 'd', 0, 0, 0, 0},
	[8]byte{'i', 'b', 'A', 'w', 0, 0, 0, 0},
	[8]byte{'i', 'q', 'A', 'b', 0, 0, 0, 0},
	[8]byte{'i', 'q', 'A', 'd', 0, 0, 0, 0},
	[8]byte{'i', 'q', 'A', 'q', 0, 0, 0, 0},
	[8]byte{'i', 'q', 'A', 'w', 0, 0, 0, 0},
	[8]byte{'i', 'w', 'i', 'b', 0, 0, 0, 0},
	[8]byte{'m', '1', 'b', 'o', 0, 0, 0, 0},
	[8]byte{'m', '1', 'y', 'o', 0, 0, 0, 0},
	[8]byte{'m', '0', 'i', '0', 0, 0, 0, 0},
	[8]byte{'m', '0', 'i', 'b', 0, 0, 0, 0},
	[8]byte{'m', '0', 'r', '0', 0, 0, 0, 0},
	[8]byte{'m', '0', 'y', '0', 0, 0, 0, 0},
	[8]byte{'m', 'b', 'i', 'b', 0, 0, 0, 0},
	[8]byte{'m', 'b', 'r', 'b', 0, 0, 0, 0},
	[8]byte{'m', 'd', 'r', 'd', 0, 0, 0, 0},
	[8]byte{'m', 'd', 'y', 'o', 0, 0, 0, 0},
	[8]byte{'m', 'h', 'y', 'h', 0, 0, 0, 0},
	[8]byte{'m', 'o', 'y', 'o', 0, 0, 0, 0},
	[8]byte{'m', 'p', 's', 'w', 0, 0, 0, 0},
	[8]byte{'m', 'q', 'r', 'q', 0, 0, 0, 0},
	[8]byte{'m', 'q', 'x', 'q', 0, 0, 0, 0},
	[8]byte{'m', 'q', 'y', 'o', 0, 0, 0, 0},
	[8]byte{'m', 'w', 's', 'w', 0, 0, 0, 0},
	[8]byte{'r', '0', 'A', '0', 0, 0, 0, 0},
	[8]byte{'r', '0', 'i', '0', 0, 0, 0, 0},
	[8]byte{'r', '0', 'i', 'b', 0, 0, 0, 0},
	[8]byte{'r', '0', 'm', '1', 0, 0, 0, 0},
	[8]byte{'r', '0', 'm', '0', 0, 0, 0, 0},
	[8]byte{'r', '0', 'm', 'd', 0, 0, 0, 0},
	[8]byte{'r', '0', 'm', 'q', 0, 0, 0, 0},
	[8]byte{'r', '0', 'm', 'w', 0, 0, 0, 0},
	[8]byte{'r', '0', 'r', '0', 0, 0, 0, 0},
	[8]byte{'r', '0', 's', 'w', 0, 0, 0, 0},
	[8]byte{'r', '0', 'v', '0', 0, 0, 0, 0},
	[8]byte{'r', '0', 'v', 'b', 0, 0, 0, 0},
	[8]byte{'r', '0', 'v', 'w', 0, 0, 0, 0},
	[8]byte{'r', '0', 'y', '0', 0, 0, 0, 0},
	[8]byte{'r', '0', 'y', 'o', 0, 0, 0, 0},
	[8]byte{'r', 'b', 'i', 'b', 0, 0, 0, 0},
	[8]byte{'r', 'b', 'm', 'b', 0, 0, 0, 0},
	[8]byte{'r', 'b', 'r', 'b', 0, 0, 0, 0},
	[8]byte{'r', 'b', 'v', 'b', 0, 0, 0, 0},
	[8]byte{'r', 'd', 'W', 'd', 0, 0, 0, 0},
	[8]byte{'r', 'd', 'c', 'd', 0, 0, 0, 0},
	[8]byte{'r', 'd', 'd', 'd', 0, 0, 0, 0},
	[8]byte{'r', 'd', 'i', 'd', 0, 0, 0, 0},
	[8]byte{'r', 'd', 'm', 'd', 0, 0, 0, 0},
	[8]byte{'r', 'd', 'm', 'q', 0, 0, 0, 0},
	[8]byte{'r', 'd', 'v', 'w', 0, 0, 0, 0},
	[8]byte{'r', 'd', 'x', 'q', 0, 0, 0, 0},
	[8]byte{'r', 'd', 'y', 'o', 0, 0, 0, 0},
	[8]byte{'r', 'q', 'W', 'q', 0, 0, 0, 0},
	[8]byte{'r', 'q', 'c', 'q', 0, 0, 0, 0},
	[8]byte{'r', 'q', 'd', 'q', 0, 0, 0, 0},
	[8]byte{'r', 'q', 'i', 'q', 0, 0, 0, 0},
	[8]byte{'r', 'q', 'm', 'd', 0, 0, 0, 0},
	[8]byte{'r', 'q', 'm', 'o', 0, 0, 0, 0},
	[8]byte{'r', 'q', 'm', 'q', 0, 0, 0, 0},
	[8]byte{'r', 'q', 'v', 'd', 0, 0, 0, 0},
	[8]byte{'r', 'q', 'v', 'q', 0, 0, 0, 0},
	[8]byte{'r', 'q', 'y', 'o', 0, 0, 0, 0},
	[8]byte{'r', 'w', 'i', 'w', 0, 0, 0, 0},
	[8]byte{'r', 'w', 'm', 'b', 0, 0, 0, 0},
	[8]byte{'s', 'w', 'm', 'p', 0, 0, 0, 0},
	[8]byte{'s', 'w', 'm', 'w', 0, 0, 0, 0},
	[8]byte{'s', 'w', 'r', 'w', 0, 0, 0, 0},
	[8]byte{'u', 'q', 'x', 'q', 0, 0, 0, 0},
	[8]byte{'v', '0', 'B', 'b', 0, 0, 0, 0},
	[8]byte{'v', '0', 'i', '0', 0, 0, 0, 0},
	[8]byte{'v', '0', 'i', 'b', 0, 0, 0, 0},
	[8]byte{'v', '0', 'r', '0', 0, 0, 0, 0},
	[8]byte{'v', 'b', 'B', 'b', 0, 0, 0, 0},
	[8]byte{'v', 'b', 'i', 'b', 0, 0, 0, 0},
	[8]byte{'v', 'b', 'r', 'b', 0, 0, 0, 0},
	[8]byte{'v', 'd', 'x', 'q', 0, 0, 0, 0},
	[8]byte{'v', 'd', 'y', 'o', 0, 0, 0, 0},
	[8]byte{'v', 'q', 'r', 'q', 0, 0, 0, 0},
	[8]byte{'v', 'q', 'x', 'q', 0, 0, 0, 0},
	[8]byte{'v', 'q', 'y', 'o', 0, 0, 0, 0},
	[8]byte{'w', 'h', 'y', 'h', 0, 0, 0, 0},
	[8]byte{'w', 'o', 'y', 'o', 0, 0, 0, 0},
	[8]byte{'x', 'q', 'i', 'b', 0, 0, 0, 0},
	[8]byte{'x', 'q', 'm', 'q', 0, 0, 0, 0},
	[8]byte{'x', 'q', 'u', 'q', 0, 0, 0, 0},
	[8]byte{'x', 'q', 'v', 'd', 0, 0, 0, 0},
	[8]byte{'x', 'q', 'v', 'q', 0, 0, 0, 0},
	[8]byte{'x', 'q', 'w', 'o', 0, 0, 0, 0},
	[8]byte{'x', 'q', 'x', 'q', 0, 0, 0, 0},
	[8]byte{'x', 'q', 'y', 'o', 0, 0, 0, 0},
	[8]byte{'y', '0', 'm', '0', 0, 0, 0, 0},
	[8]byte{'y', '0', 'm', 'b', 0, 0, 0, 0},
	[8]byte{'y', '0', 'm', 'd', 0, 0, 0, 0},
	[8]byte{'y', '0', 'm', 'w', 0, 0, 0, 0},
	[8]byte{'y', '0', 'w', '0', 0, 0, 0, 0},
	[8]byte{'y', '0', 'w', 'o', 0, 0, 0, 0},
	[8]byte{'y', '0', 'y', 'o', 0, 0, 0, 0},
	[8]byte{'y', 'h', 'm', 'h', 0, 0, 0, 0},
	[8]byte{'y', 'h', 'm', 'o', 0, 0, 0, 0},
	[8]byte{'y', 'h', 'm', 'q', 0, 0, 0, 0},
	[8]byte{'y', 'h', 'w', 'h', 0, 0, 0, 0},
	[8]byte{'y', 'h', 'y', 'o', 0, 0, 0, 0},
	[8]byte{'y', 'o', 'i', 'b', 0, 0, 0, 0},
	[8]byte{'y', 'o', 'm', '1', 0, 0, 0, 0},
	[8]byte{'y', 'o', 'm', '0', 0, 0, 0, 0},
	[8]byte{'y', 'o', 'm', 'd', 0, 0, 0, 0},
	[8]byte{'y', 'o', 'm', 'o', 0, 0, 0, 0},
	[8]byte{'y', 'o', 'm', 'q', 0, 0, 0, 0},
	[8]byte{'y', 'o', 'm', 'w', 0, 0, 0, 0},
	[8]byte{'y', 'o', 'u', 'q', 0, 0, 0, 0},
	[8]byte{'y', 'o', 'v', 'd', 0, 0, 0, 0},
	[8]byte{'y', 'o', 'v', 'q', 0, 0, 0, 0},
	[8]byte{'y', 'o', 'w', 'o', 0, 0, 0, 0},
	[8]byte{'y', 'o', 'x', 'q', 0, 0, 0, 0},
	[8]byte{'y', 'o', 'y', '0', 0, 0, 0, 0},
	[8]byte{'y', 'o', 'y', 'o', 0, 0, 0, 0},
	[8]byte{'A', '0', 'B', 'd', 'C', 'd', 0, 0},
	[8]byte{'A', 'q', 'B', 'd', 'C', 'd', 0, 0},
	[8]byte{'m', '0', 'y', '0', 'y', '0', 0, 0},
	[8]byte{'m', 'b', 'y', 'o', 'i', 'b', 0, 0},
	[8]byte{'m', 'q', 'y', 'o', 'i', 'b', 0, 0},
	[8]byte{'m', 'w', 'y', 'o', 'i', 'b', 0, 0},
	[8]byte{'r', '0', 'r', '0', 'v', '0', 0, 0},
	[8]byte{'r', '0', 'v', '0', 'i', '0', 0, 0},
	[8]byte{'r', '0', 'v', '0', 'i', 'b', 0, 0},
	[8]byte{'r', '0', 'v', '0', 'i', 'd', 0, 0},
	[8]byte{'r', '0', 'v', '0', 'r', '0', 0, 0},
	[8]byte{'r', 'd', 'x', 'q', 'i', 'b', 0, 0},
	[8]byte{'r', 'd', 'y', 'o', 'i', 'b', 0, 0},
	[8]byte{'r', 'q', 'y', 'o', 'i', 'b', 0, 0},
	[8]byte{'v', '0', 'r', '0', 'B', 'b', 0, 0},
	[8]byte{'v', '0', 'r', '0', 'i', 'b', 0, 0},
	[8]byte{'v', 'd', 'y', 'o', 'i', 'b', 0, 0},
	[8]byte{'v', 'q', 'y', 'o', 'i', 'b', 0, 0},
	[8]byte{'w', 'o', 'y', '0', 'i', 'b', 0, 0},
	[8]byte{'w', 'o', 'y', 'h', 'i', 'b', 0, 0},
	[8]byte{'x', 'q', 'm', '1', 'i', 'b', 0, 0},
	[8]byte{'x', 'q', 'r', 'd', 'i', 'b', 0, 0},
	[8]byte{'x', 'q', 'u', 'q', 'i', 'b', 0, 0},
	[8]byte{'x', 'q', 'v', 'w', 'i', 'b', 0, 0},
	[8]byte{'y', '0', 'k', '0', 'y', '0', 0, 0},
	[8]byte{'y', '0', 'l', '0', 'y', '0', 0, 0},
	[8]byte{'y', '0', 'l', 'o', 'y', '0', 0, 0},
	[8]byte{'y', '0', 'w', '0', 'i', 'b', 0, 0},
	[8]byte{'y', '0', 'y', '0', 'i', 'b', 0, 0},
	[8]byte{'y', '0', 'y', '0', 'm', '0', 0, 0},
	[8]byte{'y', '0', 'y', '0', 'w', '0', 0, 0},
	[8]byte{'y', '0', 'y', '0', 'w', 'o', 0, 0},
	[8]byte{'y', 'h', 'w', 'h', 'i', 'b', 0, 0},
	[8]byte{'y', 'h', 'y', 'h', 'w', 'h', 0, 0},
	[8]byte{'y', 'o', 'i', 'b', 'i', 'b', 0, 0},
	[8]byte{'y', 'o', 'k', '0', 'y', 'o', 0, 0},
	[8]byte{'y', 'o', 'm', '1', 'i', 'b', 0, 0},
	[8]byte{'y', 'o', 'm', 'd', 'i', 'b', 0, 0},
	[8]byte{'y', 'o', 'm', 'q', 'i', 'b', 0, 0},
	[8]byte{'y', 'o', 'm', 'w', 'i', 'b', 0, 0},
	[8]byte{'y', 'o', 'r', 'd', 'i', 'b', 0, 0},
	[8]byte{'y', 'o', 'r', 'w', 'i', 'b', 0, 0},
	[8]byte{'y', 'o', 'v', 'b', 'i', 'b', 0, 0},
	[8]byte{'y', 'o', 'v', 'd', 'i', 'b', 0, 0},
	[8]byte{'y', 'o', 'v', 'q', 'i', 'b', 0, 0},
	[8]byte{'y', 'o', 'w', 'o', 'i', 'b', 0, 0},
	[8]byte{'y', 'o', 'w', 'o', 'y', 'o', 0, 0},
	[8]byte{'y', 'o', 'y', 'o', 'i', 'b', 0, 0},
	[8]byte{'y', 'o', 'y', 'o', 'm', 'd', 0, 0},
	[8]byte{'y', 'o', 'y', 'o', 'm', 'q', 0, 0},
	[8]byte{'y', 'o', 'y', 'o', 'v', '0', 0, 0},
	[8]byte{'y', 'o', 'y', 'o', 'w', 'o', 0, 0},
	[8]byte{'y', 'o', 'y', 'o', 'y', 'o', 0, 0},
	[8]byte{'y', '0', 'y', '0', 'w', '0', 'i', 'b'},
	[8]byte{'y', '0', 'y', '0', 'w', '0', 'y', '0'},
	[8]byte{'y', '0', 'y', '0', 'y', '0', 'w', '0'},
	[8]byte{'y', 'h', 'y', 'h', 'w', 'h', 'i', 'b'},
	[8]byte{'y', 'h', 'y', 'h', 'w', 'o', 'i', 'b'},
	[8]byte{'y', 'o', 'y', 'o', 'i', 'b', 'i', 'b'},
	[8]byte{'y', 'o', 'y', 'o', 'm', 'd', 'i', 'b'},
	[8]byte{'y', 'o', 'y', 'o', 'm', 'd', 'y', 'o'},
	[8]byte{'y', 'o', 'y', 'o', 'm', 'q', 'i', 'b'},
	[8]byte{'y', 'o', 'y', 'o', 'm', 'q', 'y', 'o'},
	[8]byte{'y', 'o', 'y', 'o', 'r', 'd', 'i', 'b'},
	[8]byte{'y', 'o', 'y', 'o', 'v', 'b', 'i', 'b'},
	[8]byte{'y', 'o', 'y', 'o', 'v', 'd', 'i', 'b'},
	[8]byte{'y', 'o', 'y', 'o', 'v', 'q', 'i', 'b'},
	[8]byte{'y', 'o', 'y', 'o', 'v', 'w', 'i', 'b'},
	[8]byte{'y', 'o', 'y', 'o', 'w', 'o', 'i', 'b'},
	[8]byte{'y', 'o', 'y', 'o', 'w', 'o', 'y', 'o'},
	[8]byte{'y', 'o', 'y', 'o', 'y', 'o', 'i', 'b'},
	[8]byte{'y', 'o', 'y', 'o', 'y', 'o', 'm', 'd'},
	[8]byte{'y', 'o', 'y', 'o', 'y', 'o', 'm', 'q'},
	[8]byte{'y', 'o', 'y', 'o', 'y', 'o', 'w', 'o'},
	[8]byte{'y', 'o', 'y', 'o', 'y', 'o', 'y', 'o'},
}
